In [5]:
import numpy as np

In [7]:
mt = np.array ([12,34,26,18,10])
print(mt)
print(type(mt))

[12 34 26 18 10]
<class 'numpy.ndarray'>


In [9]:
# Cria o array com um tipo específico
# Cria o array como float de 64 bits

mtfloat = np.array([1,2,3], dtype = np.float64)
print(mtfloat)
print(type(mtfloat))

mint = np.array([1,2,3], dtype = np.int32)
print(mint)
print(type(mint))

[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


In [11]:
# muda tipo do array
# Podemos transformar tipos de dados de arrays

mtnew = np.array([1.4, 3.6, -5.1, 9.42, 4.99999])
print(mtnew)

# quando transformamos de float para int os valores são truncados
mtnewint = mtnew.astype(np.int32)
print(mtnewint)

[ 1.4      3.6     -5.1      9.42     4.99999]
[ 1  3 -5  9  4]


In [21]:
# Criar arrays vazios tipificados
# Empty significa que não são inicializados, não que são vazios

vazio = np.empty([3,2], dtype = int)
print(vazio)
print("------")

# Cria uma maatriz 4x3 com valores zero
zeros = np.zeros([4,3])
print(zeros)
print("------")

# Cria com valores igual a um
um = np.ones([5,7])
print(um)
print("-------")

# Cria uma matriz quadrada com diagonal principal com valores 1 e os outros valores 0
diagonal = np.eye(5)
print(diagonal)

[[         0 1072693248]
 [         0 1073741824]
 [         0 1074266112]]
------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
------
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
-------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [27]:
# Valores aleatórios entre zero e um 
ale = np.random.random((5))
print(ale)
print("-------")

# Valors aleatórios distr. normal contedno negativos
ale2 = np.random.randn((5))
print(ale2)
print("-------")

# Valores aleatórios 3 x 4
ale3 = (10*np.random.random((3,4)))
print(ale3)

[0.10331774 0.04539649 0.48528515 0.03207046 0.60841829]
-------
[ 0.38844803  0.53763073 -1.18781802  0.50259605 -0.57606647]
-------
[[3.15733592 9.14132306 3.61597353 3.55603492]
 [9.68113027 1.20688263 8.42277908 5.93366012]
 [4.96079392 0.9298435  1.53218455 4.19343885]]


In [31]:
# Outra forma de gerar aleatórios
# Uso de semente

gnr = np.random.default_rng(1)
ale5 = gnr.random(3)

# Gerar inteiros
ale6 = gnr.integers(10, size=(3,4))
print(ale6)

[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


In [33]:
# Unique remove repetições
j = np.array([11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 18, 19, 20])
j = np.unique(j)
print(j)

[11 12 13 14 15 16 17 18 19 20]


In [37]:
# Transposição, rearranja um conjunto de 15 elementos de 0 a 14
# em 3 linhas e 5 colunas
f = np.arange(15).reshape((3,5))
# Mostra a matriz transposta entre linha e coluna
print(f)
print("-------")
s = f.T
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
-------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
